module.exports = {
    EMAIL_MUST_VALID: 'Email Must be Valid',
    EMAIL_ALREADY_EXISTS: "Email Already Exists",
    OTP_SEND_SECCUSSFULLY: "Otp Send Succesfully",
    OTP_VERIFIED: "Otp Verified",
    WRONG_OTP: "Wrong Otp",
    DATA_NOT_FOUND: "Data Not Found!",
    NO_SUBCATEGORY_FOUND: "No Subcategory Found",
    ERROR: 'Error',
    OTP_MUST_BE_6_DIGIT: 'OTP Must Be 6 digits',
    NAME_MUST_BE_ATLEAST_3_CHARACTER:'Name is must be atleast 3 character',
    REMARK_MUST_BE_ATLEAST_3_CHARACTER:'Remark is must be atleast 3 character',
    ADDRESS_MUST_BE_ATLEAST_5_CHARACTER:'Address is must be atleast 5 character',
    SPECIAL_NOTES_MUST_BE_ATLEAST_10_CHARACTER:'Special Notes is must be atleast 10 character',
    DESC_MUST_BE_ATLEAST_10_CHARACTER:'Description is must be atleast 10 character',
    NUMBER_MUST_BE_10_DIGITS:'Number must be 10 digits',
    QR_CODE_MUST_NOT_BE_EMPTY:'QR Code must not be Empty',
    QR_CODE_GROUP_ID_MUST_NOT_BE_EMPTY:'QR Code Group ID must not be Empty',
    COUNTRY_CODE_MUST_NOT_BE_EMPTY:'Country Code must not be Empty',
    AMOUNT_MUST_NOT_BE_EMPTY:'Amount must not be Empty',
    QUANTITY_MUST_NOT_BE_EMPTY:'Quantity must not be Empty',
    ORDER_TYPE_MUST_NOT_BE_EMPTY:'Order Type must not be Empty',
    QR_CODE_GROUP_MUST_NOT_BE_EMPTY:'QR Code Group must not be Empty',
    GENDER_MUST_NOT_BE_EMPTY:'Gender must not be Empty',
    AGE_MUST_NOT_EMPTY:'Age Must not be empty',
    USER_UPDATED_SUCCESSFULLY:'User Updated Successfully',
    RESTAURANT_UPDATED_SUCCESSFULLY:'Restaurant Updated Successfully',
    ADD_ORDER_SUCCESSFULLY:"Add Order Successfully",
    ADD_MENU_SUCCESSFULLY:"Add Menu Successfully",
    ORDER_UPDATED_SUCCESSFULLY:'Order Updated Successfully',
    MENU_UPDATED_SUCCESSFULLY:'Menu Updated Successfully',
    SECTION_UPDATED_SUCCESSFULLY:'Section Updated Successfully',
    SECTION_ITEM_UPDATED_SUCCESSFULLY:'Section Item Updated Successfully',
    GET_DATA_SUCCESSFULLY:"Get Data Sucessfully",
    FAILED_TO_DELETE_DATA:'Failed to Delete Data',
    DATA_DELETED_SUCCESSFULLY:"Data Deleted Successfully",
    PASSWORD_MUST_MIN_8_CHARACTER:"Password Must be Min 8 Character",
    LOGIN_SUCCESSFULLY:"Login Successfully",
    INCORRECT_PASSWORD:"Incorrect Password",
    CONFIRM_PASSWORD_MUST_MIN_8_CHARACTER:"Confirm Password Must be Min 8 Character",
    UNAUTHORIZED_USER:"Unauthorized User",
    PASSWORD_DO_NOT_MATCH:"The passwords do not match",
    PASSWORD_CHANGE_SUCCESSFULLY:"Password Change Successfully",
    OLDPASSWORD_WRONG:"Old Password Is wrong",
    WRONG_EMAIL:"You Entered Wrong Email",
    MENUID_MUST_NOT_EMPTY:'Menu ID is must be not Empty',
    SECTIONID_MUST_NOT_EMPTY:'Section ID is must be not Empty',
    ALLERGIES_MUST_NOT_EMPTY:'Allergies is must be not Empty',
    PRICE_MUST_NOT_EMPTY:'Price is must be not Empty',
    RECOMMENDED_ITEMS_MUST_NOT_EMPTY:'Recommended Items is must be not Empty',
    DATA_INSERTED_SUCCESSFULLY:"Data inserted successfully",
    SECTION_MODIFIED_SUCCESSFULLY:"Section Modified Successfullly",
    ERROR_DELETING_SECTION:"Error Deleting the Section",
    ERROR_DELETING_SECTIONITEN:"Error Deleting the Section Item",
    SECTION_DELETED:"Section has been deleted successfully",
    SECTIONITEMS_CREATED_SUCCESSFULLY:"Section Items Created Successfully",
    ADD_MODIFIER_SUCCESSFULLY:"Modifier Added Successfully",
    MODIFIER_UPDATED_SUCCESSFULLY:"Modifier Updated Successfully",
    MODIFIER_MUST_NOT_EMPTY:'Modifier is must be not Empty',
    GROUP_TYPE_MUST_BE_ATLEAST_3_CHARACTER:"group type must be atleast 3 character",
    GROUP_NAME_MUST_BE_ATLEAST_3_CHARACTER:"gropu name must be atleast 3 digit ",
    ARABIC_GROUP_NAME_MUST_NOT_EMPTY:"arabic group name must be atleast 3 digit",
    ADD_OGROUP_SUCCESSFULLY:"add orderGroup successfully",
    ADD_QRCODES_SUCCESSFULLY:"QR Code Added Successfully",
    QRCODES_UPDATED_SUCCESSFULLY:"QR Code Updated Successfully",
    INTERNAL_ERROR:"internal error",
    NO_DATA_FOUND:"No data found",
    Group_UPDATED_SUCCESSFULLY:'group Updated Successfully',
    STATUS_UPDATED_SUCCESSFULLY:'status Updated Successfully'
}
